### ISSUE TITLE
您好，我在尝试使用您的程序，可是使用您在readme上写的使用方式后发生了异常

### ISSUE THREAD

**Issue by FlyRenxing** [zongwei007/jms-redis#2]
您好，我在尝试使用您的程序，可是使用您在readme上写的使用方式后发生了异常，您可以帮我看一下是哪里错了吗?
redis-cil：
127.0.0.1:6379> MONITOR
OK
1619359494.759739 [0 127.0.0.1:54674] "MULTI"
1619359494.775513 [0 127.0.0.1:54674] "HMSET" "JMS:QUEUE:Queue:ID:otwvLbBmQXOaXCdrKxVkYA" "JMSTimestamp" "1619359494688" "JMSPriority" "0" "JMSDeliveryMode" "2" "JMSRedelivered" "false" "JMSDestination" "QUEUE:Queue" "JMSType" "Text"
1619359494.775622 [0 127.0.0.1:54674] "SET" "JMS:QUEUE:Queue:ID:otwvLbBmQXOaXCdrKxVkYA:BODY" "Queue Message"
1619359494.775650 [0 127.0.0.1:54674] "LPUSH" "JMS:QUEUE:Queue" "ID:otwvLbBmQXOaXCdrKxVkYA"
1619359494.775672 [0 127.0.0.1:54674] "CLIENT" "REPLY" "OFF"
1619359494.775685 [0 127.0.0.1:54674] "EXEC"
1619359494.775691 [0 127.0.0.1:54674] "CLIENT" "REPLY" "ON"

java异常：
Exception in thread "main" org.redisson.client.RedisException: ERR Syntax error, try CLIENT (LIST | KILL ip:port | GETNAME | SETNAME connection-name). channel: [id: 0x1916bf42, L:/127.0.0.1:54674 - R:127.0.0.1/127.0.0.1:6379] command: (EXEC), params: null
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:405)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:266)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:207)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zongwei007** [comment]
@FlyRenxing JDK8 环境下，使用 Redisson 3.12.2 连接 Redis 6.0.9 没有发现问题。目前在运行的环境中，也有连接 Redis 5 的，工作正常。你是使用什么环境测试？

**Comment by FlyRenxing** [comment]
您好，感谢！我的redis用的是windows版，我更换了redis版本Redis-x64-3.2.100后不会报异常了。之前是3.0.504。

还有个问题想请教下，怎样实现监听消息呢？我尝试实现MessageListener接口可是我不知道在哪指定destination

**Comment by zongwei007** [comment]
@FlyRenxing 使用这部分查 JMS 相关的资料即可，如 https://www.cnblogs.com/chenpi/p/5559349.html。

实际上，如果不打算学习 JMS 的使用，只是需要一套消息生产、消费服务的机制的话，直接使用 Redisson + Redis 5.x+ 的组合会比使用这个库来得可靠。这个库最早是在 Redis 3.x 的背景下写的，在 Redis  5.0 已原生支持带 ack 的生产、消费模式后已无太大用途。
